# Generated by Django 5.0.3 on 2024-03-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=30, null=True)),
                ('condition', models.CharField(max_length=30, null=True)),
                ('transmission', models.CharField(max_length=30, null=True)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('engine', models.CharField(max_length=30, null=True)),
                ('colors', models.CharField(max_length=100, null=True)),
                ('body_style', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('availability', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='base.car')),
            ],
        ),
    ]
