# Generated by Django 5.0.3 on 2024-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
