# Generated by Django 5.0.3 on 2024-03-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_car_horsepower_alter_car_body_style_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
