# Generated by Django 5.0.3 on 2024-03-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_remove_carimage_car_delete_car_delete_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('condition', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=30)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine', models.CharField(max_length=30)),
                ('colors', models.CharField(max_length=100)),
                ('body_style', models.CharField(max_length=30)),
                ('price', models.IntegerField(null=True)),
                ('availability', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='base.car')),
            ],
        ),
    ]
