# Generated by Django 5.0.3 on 2024-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('', 'Body Style'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Pickup Truck', 'Pickup Truck')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.CharField(choices=[('', 'Colors'), ('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('Yellow', 'Yellow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('First Hand', 'First Hand'), ('Second Hand', 'Second Hand')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('BS3', 'BS3'), ('BS4', 'BS4'), ('BS5', 'BS5'), ('BS6', 'BS6')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(choices=[('27', '27'), ('20', '20'), ('15', '15'), ('10', '10')], decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Bluetooth', 'Bluetooth'), ('WiFi', 'WiFi')], max_length=30),
        ),
    ]
