# Generated by Django 5.0.3 on 2024-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_car_body_style_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(null=True),
        ),
    ]
